In [1]:
%load_ext bigquery_magics

import bigquery_magics
bigquery_magics.context.project = "k-move1-kyungpil"

## 1. STRUCTデータ型

`STRUCT`は、複数の項目を一つの列にまとめて保存するデータ型である。  
Pythonの`dict`型に似ている。

In [ ]:
%%bigquery

WITH tmp AS (
    SELECT
        STRUCT(
            '千尋' AS name,
            20 AS age,
            '東京' AS city
        ) AS person,
        'JAPAN' AS country

    UNION ALL

    SELECT
        STRUCT(
            'ハウル' AS name,
            25 AS age,
            '京都' AS city
        ) AS person,
        'JAPAN' AS country
)

SELECT
    person,
    country
FROM tmp;

-- `person`列の中に`name`・`age`・`city`がまとめて保存される。
-- `country`は`person`とは別の一般列である。

Query is running:   0%|          |

Downloading:   0%|          |

                                     person country
0   {'name': '千尋', 'age': 20, 'city': '東京'}   JAPAN
1  {'name': 'ハウル', 'age': 25, 'city': '京都'}   JAPAN

#### 1）ドット演算子でSTRUCT内の値を個別に取得する

In [4]:
%%bigquery

WITH tmp AS (
    SELECT
        STRUCT(
            '千尋' AS name,
            20 AS age,
            '東京' AS city
        ) AS person,
        'JAPAN' AS country

    UNION ALL

    SELECT
        STRUCT(
            'ハウル' AS name,
            25 AS age,
            '京都' AS city
        ) AS person,
        'JAPAN' AS country
)

SELECT
    person.name,
    person.city,
    country
FROM tmp;

Query is running:   0%|          |

Downloading:   0%|          |

  name city country
0   千尋   東京   JAPAN
1  ハウル   京都   JAPAN