In [1]:
%load_ext bigquery_magics

In [2]:
%%bigquery

SELECT 1 AS result;

Query is running:   0%|          |

Downloading:   0%|          |

   result
0       1

In [4]:
%%bigquery

WITH score_data AS (
    SELECT '국어' AS subject, 90 AS score UNION ALL
    SELECT '영어', 85 UNION ALL
    SELECT '수학', 100
)
SELECT *
FROM score_data
PIVOT (
    MAX(score)
    FOR subject IN ('국어', '영어', '수학')
);

Query is running:   0%|          |

Downloading:   0%|          |

   국어  영어   수학
0  90  85  100