※ Series型のすべてのメソッドリファレンスは以下で確認

https://pandas.pydata.org/docs/reference/series.html

<br>

DataFrame = 複数のSeriesが集まった2次元データ構造  
Series = DataFrameから1つの列を選択した1次元データ構造

<span style="color:red;">df["列名"] → Seriesを返す</span>  
<span style="color:red;">df[["列名"]] → DataFrameを返す</span>

In [2]:
import pandas as pd

df = pd.DataFrame({
    "名前": ["千尋", "キキ", "ハウル"],
    "点数": [80, 90, 75]
})


# 1列を選択 → Series
s = df["点数"]

display(s)
display(type(s))

print()

# 1列をリスト形式で選択 → DataFrame
df2 = df[["点数"]]

display(df2)
display(type(df2))

0    80
1    90
2    75
Name: 点数, dtype: int64

pandas.Series

   点数
0  80
1  90
2  75

pandas.DataFrame

<br>

<span style="color:red;">
※ <code>DataFrameは複数のSeriesが集まった2次元データ構造</code>であるため、Seriesで使用するメソッドと、DataFrameで使用するメソッドは非常に似ている。
</span>

#### ※ SeriesとDataFrameの主な対応メソッド

<table align="left">
  <thead>
    <tr>
      <th>機能</th>
      <th><code>Series</code></th>
      <th><code>DataFrame</code></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>欠損値の確認</td>
      <td>s.isna()</td>
      <td>df.isna()</td>
    </tr>
    <tr>
      <td>欠損値の個数</td>
      <td>s.isna().sum()</td>
      <td>df.isna().sum()</td>
    </tr>
    <tr>
      <td>欠損値の削除</td>
      <td>s.dropna()</td>
      <td>df.dropna()</td>
    </tr>
    <tr>
      <td>欠損値の置換</td>
      <td>s.fillna(0)</td>
      <td>df.fillna(0)</td>
    </tr>
    <tr>
      <td>並べ替え</td>
      <td>s.sort_values()</td>
      <td>df.sort_values()</td>
    </tr>
    <tr>
      <td>重複の削除</td>
      <td>s.drop_duplicates()</td>
      <td>df.drop_duplicates()</td>
    </tr>
    <tr>
      <td>統計</td>
      <td>s.mean()</td>
      <td>df.mean()</td>
    </tr>
    <tr>
      <td>累積最大値</td>
      <td>s.cummax()</td>
      <td>df.cummax()</td>
    </tr>
    <tr>
      <td>累積合計</td>
      <td>s.cumsum()</td>
      <td>df.cumsum()</td>
    </tr>
    <tr>
      <td>値の個数</td>
      <td>s.value_counts()</td>
      <td>df.value_counts()</td>
    </tr>
    <tr>
      <td>型変換</td>
      <td>s.astype()</td>
      <td>df.astype()</td>
    </tr>
    <tr>
      <td>apply()</td>
      <td>値 / 要素に適用</td>
      <td>行 / 列単位で適用可能</td>
    </tr>
  </tbody>
</table>

<br clear="left">

<br>

## 1. 実習用データセット

In [3]:
import pandas as pd
import numpy as np


df = pd.DataFrame({
    "従業員ID": [101, 102, 103, 104, 105, 106, 107, 108],
    "名前": ["千尋", "キキ", "ハウル", "ソフィー",
            "アシタカ", "サン", "ポルコ", "ナウシカ"],
    "部署": ["開発", "営業", "開発", "人事",
            "営業", "開発", "営業", "人事"],
    "性別": ["男", "女", "男", "女", "男", "女", "女", "男"],
    "売上": [550, 320, np.nan, 780, 1200, 650, 920, np.nan],
    "勤務時間": [160, 172, 168, 155, 180, 150, 172, 158],
    "等級": ["B", "A", "B", "C", "A", "C", "A", None],
    "入社年度": [2020, 2019, 2021, 2022, 2018, 2023, 2019, 2022]
})

display(df)

   従業員ID    名前  部署 性別      売上  勤務時間   等級  入社年度
0    101    千尋  開発  男   550.0   160    B  2020
1    102    キキ  営業  女   320.0   172    A  2019
2    103   ハウル  開発  男     NaN   168    B  2021
3    104  ソフィー  人事  女   780.0   155    C  2022
4    105  アシタカ  営業  男  1200.0   180    A  2018
5    106    サン  開発  女   650.0   150    C  2023
6    107   ポルコ  営業  女   920.0   172    A  2019
7    108  ナウシカ  人事  男     NaN   158  NaN  2022

<br>

## 2. Seriesメソッドの分類

<div style="background-color:#f4f5f5; padding:0; color:#111111; font-family:monospace;">

<div style="background-color:#eaecee; padding:7px 16px;">
［データ探索］
</div>

<div style="background-color:#f4f5f5; padding:7px 16px;">
head → tail → info → describe
</div>

<div style="background-color:#eaecee; padding:7px 16px;">
&nbsp;
</div>

<div style="background-color:#f4f5f5; padding:7px 16px;">
［統計］
</div>

<div style="background-color:#eaecee; padding:7px 16px;">
mean / median / mode
</div>

<div style="background-color:#f4f5f5; padding:7px 16px;">
sum / min / max
</div>

<div style="background-color:#eaecee; padding:7px 16px;">
std / var
</div>

<div style="background-color:#f4f5f5; padding:7px 16px;">
count / quantile
</div>

<div style="background-color:#eaecee; padding:7px 16px;">
&nbsp;
</div>

<div style="background-color:#f4f5f5; padding:7px 16px;">
［カテゴリデータ］
</div>

<div style="background-color:#eaecee; padding:7px 16px;">
unique → nunique → value_counts
</div>

<div style="background-color:#f4f5f5; padding:7px 16px;">
&nbsp;
</div>

<div style="background-color:#eaecee; padding:7px 16px;">
［欠損値］
</div>

<div style="background-color:#f4f5f5; padding:7px 16px;">
isna / isnull
</div>

<div style="background-color:#eaecee; padding:7px 16px;">
notna / notnull
</div>

<div style="background-color:#f4f5f5; padding:7px 16px;">
↓
</div>

<div style="background-color:#eaecee; padding:7px 16px;">
fillna / dropna
</div>

<div style="background-color:#f4f5f5; padding:7px 16px;">
&nbsp;
</div>

<div style="background-color:#eaecee; padding:7px 16px;">
［データ変換］
</div>

<div style="background-color:#f4f5f5; padding:7px 16px;">
apply / map / replace
</div>

<div style="background-color:#eaecee; padding:7px 16px;">
where / mask
</div>

<div style="background-color:#f4f5f5; padding:7px 16px;">
&nbsp;
</div>

<div style="background-color:#eaecee; padding:7px 16px;">
［時系列・変化］
</div>

<div style="background-color:#f4f5f5; padding:7px 16px;">
shift → diff → pct_change
</div>

</div>

<br>

## 3. 実習

#### 1) 基本情報

In [ ]:
s = df["売上"]

display("sの型:", type(s))


display(df["売上"].head(2))  # デフォルト値 5
display(df["売上"].tail(2))


display(df["売上"].info())
display(df["売上"].describe())
display(df["等級"].describe())

```text
【Series型】

sの型: <class 'pandas.Series'>
--------------------------------------------------

【先頭・末尾データ】

- head(2)
0    550.0
1    320.0
Name: 売上, dtype: float64

- tail(2)
6    920.0
7      NaN
Name: 売上, dtype: float64
--------------------------------------------------

【基本情報・記述統計量】

<class 'pandas.Series'>
RangeIndex: 8 entries, 0 to 7
Series name: 売上
Non-Null Count  Dtype  
--------------  -----  
6 non-null      float64
dtypes: float64(1)
memory usage: 196.0 bytes

- 売上
count       6.000000
mean      736.666667
std       305.330422
min       320.000000
25%       575.000000
50%       715.000000
75%       885.000000
max      1200.000000
Name: 売上, dtype: float64

- 等級
count     7
unique    3
top       A
freq      3
Name: 等級, dtype: object
```

#### 2) 統計

In [ ]:
display("平均:", df["売上"].mean())
display("中央値:", df["売上"].median())

# カテゴリ型 - 最頻値は頻度が同じ場合、
# 2つ以上を返す必要があるためSeries型で返す
display("最頻値:", df["等級"].mode())
display("最頻値:", df["性別"].mode())


display("合計:", df["売上"].sum())
display("最大値:", df["売上"].max())
display("最小値:", df["売上"].min())


display("分散:", df["売上"].var())
display("標準偏差:", df["売上"].std())


display("第1四分位数:", df["売上"].quantile(0.25))
display("第2四分位数:", df["売上"].quantile(0.50))
display("第3四分位数:", df["売上"].quantile(0.75))

```text
【代表値】
- 平均: 736.6666666666666
- 中央値: 715.0
--------------------------------------------------
【最頻値】
- 等級: A
- 性別: 女 男
--------------------------------------------------
【合計・最大・最小】
- 合計: 4420.0
- 最大値: 1200.0
- 最小値: 320.0
--------------------------------------------------
【分散・標準偏差】
- 分散: 93226.66666666666
- 標準偏差: 305.33042211130333
--------------------------------------------------
【四分位数】
- 第1四分位数: 575.0
- 第2四分位数: 715.0
- 第3四分位数: 885.0
```

In [ ]:
# データ数
# Series.count()メソッド vs len()関数
display(df["売上"].count())  # NaNを除外
display(len(df["売上"]))     # NaNを含む

```text
【データ数】
- count() : 6
- len() : 8
```

#### 3) 一意な値 - カテゴリ型データで主に使用

In [ ]:
display(df["性別"].unique())
display(df["部署"].unique())

# 一意な値の個数
display(df["性別"].nunique())
display(df["部署"].nunique())

```text
【一意な値】
- 性別: <StringArray>
['男', '女']
Length: 2, dtype: str

- 部署: <StringArray>
['開発', '営業', '人事']
Length: 3, dtype: str

【一意な値の個数】
- 性別: 2
- 部署: 3
```

#### 4) 頻度 - カテゴリ型データで主に使用

In [ ]:
display(df["性別"].value_counts())
display(df["部署"].value_counts())

```text
【性別の頻度】
性別
男    4
女    4
Name: count, dtype: int64

【部署の頻度】
部署
開発    3
営業    3
人事    2
Name: count, dtype: int64
```

#### 5) 欠損値 - 欠損値の場合True

In [ ]:
display(df["売上"].isna())
display(df["売上"].isnull())

display(df["売上"].notna())   # not na
display(df["売上"].notnull()) # not null

[欠損値]
- isna(): 0    False
1    False
2     True
3    False
4    False
5    False
6    False
7     True
Name: 売上, dtype: bool

- isnull(): 0    False
1    False
2     True
3    False
4    False
5    False
6    False
7     True
Name: 売上, dtype: bool

- notna(): 0     True
1     True
2    False
3     True
4     True
5     True
6     True
7    False
Name: 売上, dtype: bool

- notnull(): 0     True
1     True
2    False
3     True
4     True
5     True
6     True
7    False
Name: 売上, dtype: bool

```text
【欠損値】
- isna(): 
0    False
1    False
2     True
3    False
4    False
5    False
6    False
7     True
Name: 売上, dtype: bool

- isnull(): 
0    False
1    False
2     True
3    False
4    False
5    False
6    False
7     True
Name: 売上, dtype: bool

- notna(): 
0     True
1     True
2    False
3     True
4     True
5     True
6     True
7    False
Name: 売上, dtype: bool

- notnull(): 
0     True
1     True
2    False
3     True
4     True
5     True
6     True
7    False
Name: 売上, dtype: bool
```

In [ ]:
# fillna - 欠損値を置換
sales = df["売上"]

# 平均値で置換
sales = sales.fillna(sales.mean())

display(sales)